// Food and cocktail menu transcribed from Jam-Roc supplied menus.
export const catalog = {
  "categories": [
    {
      "slug": "main-dishes",
      "name": "Main Dishes",
      "kind": "food",
      "sortOrder": 0
    },
    {
      "slug": "specials",
      "name": "Specials",
      "kind": "food",
      "sortOrder": 1
    },
    {
      "slug": "sides",
      "name": "Sides",
      "kind": "food",
      "sortOrder": 2
    },
    {
      "slug": "salads",
      "name": "Salads",
      "kind": "food",
      "sortOrder": 3
    },
    {
      "slug": "done-to-order",
      "name": "Done to Order",
      "kind": "food",
      "sortOrder": 4
    },
    {
      "slug": "seafood",
      "name": "Seafood",
      "kind": "food",
      "sortOrder": 5
    },
    {
      "slug": "seafood-sides",
      "name": "Seafood Sides",
      "kind": "food",
      "sortOrder": 6
    },
    {
      "slug": "cocktails",
      "name": "Cocktails",
      "kind": "drink",
      "sortOrder": 0
    },
    {
      "slug": "spirits",
      "name": "Spirits",
      "kind": "drink",
      "sortOrder": 1
    },
    {
      "slug": "beer",
      "name": "Beer",
      "kind": "drink",
      "sortOrder": 2
    },
    {
      "slug": "wine",
      "name": "Wine",
      "kind": "drink",
      "sortOrder": 3
    },
    {
      "slug": "non-alcoholic",
      "name": "Non-Alcoholic",
      "kind": "drink",
      "sortOrder": 4
    }
  ],
  "items": [
    {
      "slug": "oxtail",
      "name": "Oxtail",
      "description": "Slow-braised oxtail in a rich, savory gravy.",
      "kind": "food",
      "categorySlug": "main-dishes",
      "sortOrder": 0,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/oxtail.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "jerk-pork",
      "name": "Jerk Pork",
      "description": "Smoky jerk-seasoned pork with a bold island kick.",
      "kind": "food",
      "categorySlug": "main-dishes",
      "sortOrder": 1,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/jerk-pork.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "cowfoot",
      "name": "Cowfoot",
      "description": "A hearty Jamaican classic, slow cooked until tender.",
      "kind": "food",
      "categorySlug": "main-dishes",
      "sortOrder": 2,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/cowfoot.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "curry-goat",
      "name": "Curry Goat",
      "description": "Tender goat simmered in aromatic Jamaican curry.",
      "kind": "food",
      "categorySlug": "main-dishes",
      "sortOrder": 3,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/curry-goat.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "tripe-and-beans",
      "name": "Tripe & Beans",
      "description": "A comforting stew of tripe and butter beans.",
      "kind": "food",
      "categorySlug": "main-dishes",
      "sortOrder": 4,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/tripe-and-beans.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "fry-chicken",
      "name": "Fry Chicken",
      "description": "Golden, crisp fried chicken.",
      "kind": "food",
      "categorySlug": "main-dishes",
      "sortOrder": 5,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/fry-chicken.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "jerk-chicken",
      "name": "Jerk Chicken",
      "description": "Smoky, chargrilled chicken with Jamaican jerk seasoning.",
      "kind": "food",
      "categorySlug": "main-dishes",
      "sortOrder": 6,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/jerk-chicken.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "curry-chicken",
      "name": "Curry Chicken",
      "description": "Chicken simmered in a fragrant golden curry.",
      "kind": "food",
      "categorySlug": "main-dishes",
      "sortOrder": 7,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/curry-chicken.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "brown-stew-chicken",
      "name": "Brown Stew Chicken",
      "description": "Chicken slow simmered in a deep brown gravy.",
      "kind": "food",
      "categorySlug": "main-dishes",
      "sortOrder": 8,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/brown-stew-chicken.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "stew-peas",
      "name": "Stew Peas",
      "description": "A hearty Jamaican red pea stew.",
      "kind": "food",
      "categorySlug": "specials",
      "sortOrder": 9,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/stew-peas.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "stew-pork",
      "name": "Stew Pork",
      "description": "Tender pork in a rich, slow-cooked gravy.",
      "kind": "food",
      "categorySlug": "specials",
      "sortOrder": 10,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/stew-pork.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "pepper-steak",
      "name": "Pepper Steak",
      "description": "Savory steak strips with peppers and onions.",
      "kind": "food",
      "categorySlug": "specials",
      "sortOrder": 11,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/pepper-steak.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "bar-b-fry-wings",
      "name": "Bar-B-Fry Wings",
      "description": "Crisp fried wings finished with barbecue sauce.",
      "kind": "food",
      "categorySlug": "specials",
      "sortOrder": 12,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/bar-b-fry-wings.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "rice-and-peas",
      "name": "Rice & Peas",
      "description": "Classic Jamaican rice and peas.",
      "kind": "food",
      "categorySlug": "sides",
      "sortOrder": 13,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/rice-and-peas.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "white-rice",
      "name": "White Rice",
      "description": "Fluffy steamed white rice.",
      "kind": "food",
      "categorySlug": "sides",
      "sortOrder": 14,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/white-rice.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "boiled-banana",
      "name": "Boiled Banana",
      "description": "A traditional green banana side.",
      "kind": "food",
      "categorySlug": "sides",
      "sortOrder": 15,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/boiled-banana.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "boiled-dumpling",
      "name": "Boiled Dumpling",
      "description": "Soft, hearty Jamaican boiled dumplings.",
      "kind": "food",
      "categorySlug": "sides",
      "sortOrder": 16,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/boiled-dumpling.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "yellow-yam",
      "name": "Yellow Yam",
      "description": "Tender pieces of boiled yellow yam.",
      "kind": "food",
      "categorySlug": "sides",
      "sortOrder": 17,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/yellow-yam.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "stir-fry-vegetables",
      "name": "Stir Fry Vegetables",
      "description": "Colorful vegetables, lightly stir fried.",
      "kind": "food",
      "categorySlug": "sides",
      "sortOrder": 18,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/stir-fry-vegetables.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "fresh-salad",
      "name": "Fresh Salad",
      "description": "A crisp and refreshing side salad.",
      "kind": "food",
      "categorySlug": "sides",
      "sortOrder": 19,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/fresh-salad.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "fried-plantain",
      "name": "Fried Plantain",
      "description": "Sweet ripe plantain, fried until golden.",
      "kind": "food",
      "categorySlug": "sides",
      "sortOrder": 20,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/fried-plantain.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "garden-salad",
      "name": "Garden Salad",
      "description": "A fresh mix of crisp garden vegetables.",
      "kind": "food",
      "categorySlug": "salads",
      "sortOrder": 21,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/garden-salad.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "jerk-pork-salad",
      "name": "Jerk Pork Salad",
      "description": "Garden greens topped with smoky jerk pork.",
      "kind": "food",
      "categorySlug": "salads",
      "sortOrder": 22,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/jerk-pork-salad.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "jerk-chicken-salad",
      "name": "Jerk Chicken Salad",
      "description": "Fresh salad topped with Jamaican jerk chicken.",
      "kind": "food",
      "categorySlug": "salads",
      "sortOrder": 23,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/jerk-chicken-salad.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "grilled-salmon-salad",
      "name": "Grilled Salmon Salad",
      "description": "Grilled salmon served over fresh greens.",
      "kind": "food",
      "categorySlug": "salads",
      "sortOrder": 24,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/grilled-salmon-salad.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "wings-and-fries",
      "name": "Wings & Fries",
      "description": "Freshly prepared chicken wings with golden fries.",
      "kind": "food",
      "categorySlug": "done-to-order",
      "sortOrder": 25,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/wings-and-fries.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "grilled-salmon",
      "name": "Grilled Salmon",
      "description": "Salmon grilled to order.",
      "kind": "food",
      "categorySlug": "seafood",
      "sortOrder": 26,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/grilled-salmon.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "curry-shrimp",
      "name": "Curry Shrimp",
      "description": "Shrimp in a fragrant Jamaican curry.",
      "kind": "food",
      "categorySlug": "seafood",
      "sortOrder": 27,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/curry-shrimp.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "brown-stew-shrimp",
      "name": "Brown Stew Shrimp",
      "description": "Shrimp simmered in a savory brown sauce.",
      "kind": "food",
      "categorySlug": "seafood",
      "sortOrder": 28,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/brown-stew-shrimp.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "steamed-red-snapper",
      "name": "Whole Red Snapper",
      "description": "Prepared to order: steamed, brown stew, or escovitch.",
      "kind": "food",
      "categorySlug": "seafood",
      "sortOrder": 29,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/steamed-red-snapper.webp",
      "illustrative": true,
      "options": [
        {
          "name": "Steamed",
          "imageUrl": "assets/images/menu/steamed-red-snapper.webp"
        },
        {
          "name": "Brown Stew",
          "imageUrl": "assets/images/menu/brown-stew-red-snapper.webp"
        },
        {
          "name": "Escovitch",
          "imageUrl": "assets/images/menu/escovitch-red-snapper.webp"
        }
      ]
    },
    {
      "slug": "bammy",
      "name": "Bammy",
      "description": "Traditional Jamaican cassava rounds.",
      "kind": "food",
      "categorySlug": "seafood-sides",
      "sortOrder": 30,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/bammy.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "french-fries",
      "name": "French Fries",
      "description": "Golden, crisp-cut fries.",
      "kind": "food",
      "categorySlug": "seafood-sides",
      "sortOrder": 31,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/french-fries.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "baked-potatoes",
      "name": "Baked Potatoes",
      "description": "Tender baked potatoes with fluffy centers.",
      "kind": "food",
      "categorySlug": "seafood-sides",
      "sortOrder": 32,
      "published": false,
      "isAvailable": true,
      "imageUrl": "assets/images/menu/baked-potatoes.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "knockout-punch",
      "name": "Knockout Punch",
      "description": "We dare you.\nA bold blend of Jamaican rum and cognac, finished with ginger beer.\nIngredients: Wray & Nephew White Overproof Rum • Appleton Estate Signature • Hennessy VS • D’Ussé • Stoney Ginger Beer",
      "kind": "drink",
      "categorySlug": "cocktails",
      "published": false,
      "isAvailable": true,
      "sortOrder": 0,
      "imageUrl": "assets/images/menu/knockout-punch.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "yard-man",
      "name": "Yard Man",
      "description": "Straight Jamaican attitude.\nJamaican white overproof and Appleton rum with a ginger beer finish.\nIngredients: Wray & Nephew White Overproof Rum • Appleton Estate Signature • Stoney Ginger Beer",
      "kind": "drink",
      "categorySlug": "cocktails",
      "published": false,
      "isAvailable": true,
      "sortOrder": 1,
      "imageUrl": "assets/images/menu/yard-man.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "island-after-dark",
      "name": "Island After Dark",
      "description": "Sweet when it starts. Trouble when it finishes.\nWatermelon, red berry, and strawberry-grape spirits meet ginger beer.\nIngredients: Cîroc Summer Watermelon • Cîroc Red Berry • XXIV Strawberry Grape • Stoney Ginger Beer",
      "kind": "drink",
      "categorySlug": "cocktails",
      "published": false,
      "isAvailable": true,
      "sortOrder": 2,
      "imageUrl": "assets/images/menu/island-after-dark.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "mango-madness",
      "name": "Mango Madness",
      "description": "Vacation in a glass.\nMango and peach spirits with the lively spice of ginger beer.\nIngredients: XXIV Mango • Cîroc Peach • Stoney Ginger Beer",
      "kind": "drink",
      "categorySlug": "cocktails",
      "published": false,
      "isAvailable": true,
      "sortOrder": 3,
      "imageUrl": "assets/images/menu/mango-madness.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "blue-island",
      "name": "Blue Island",
      "description": "The drink everybody photographs.\nLuc Belaire Bleu paired with coconut vodka for a sparkling tropical mix.\nIngredients: Luc Belaire Bleu • Cîroc Coconut",
      "kind": "drink",
      "categorySlug": "cocktails",
      "published": false,
      "isAvailable": true,
      "sortOrder": 4,
      "imageUrl": "assets/images/menu/blue-island.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "bad-apple",
      "name": "Bad Apple",
      "description": "Sweet. Smooth. Dangerous.\nApple whisky and coconut vodka topped with ginger beer.\nIngredients: Crown Royal Apple • Cîroc Coconut • Stoney Ginger Beer",
      "kind": "drink",
      "categorySlug": "cocktails",
      "published": false,
      "isAvailable": true,
      "sortOrder": 5,
      "imageUrl": "assets/images/menu/bad-apple.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "kingston-knockout",
      "name": "Kingston Knockout",
      "description": "Heavy hits. Island spirit.\nJamaican rums and VSOP cognacs brought together with ginger beer.\nIngredients: Wray & Nephew White Overproof Rum • Hennessy VSOP • Rémy Martin VSOP • Appleton Estate Signature • Stoney Ginger Beer",
      "kind": "drink",
      "categorySlug": "cocktails",
      "published": false,
      "isAvailable": true,
      "sortOrder": 6,
      "imageUrl": "assets/images/menu/kingston-knockout.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "strawberry-sunset",
      "name": "Strawberry Sunset",
      "description": "Easy to order. Hard to order just one.\nStrawberry-grape and red berry spirits with sparkling Belaire Bleu.\nIngredients: XXIV Strawberry Grape • Cîroc Red Berry • Belaire Bleu",
      "kind": "drink",
      "categorySlug": "cocktails",
      "published": false,
      "isAvailable": true,
      "sortOrder": 7,
      "imageUrl": "assets/images/menu/strawberry-sunset.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "tequila-island",
      "name": "Tequila Island",
      "description": "Mexico meets the Caribbean.\nBlanco and reposado tequilas paired with Jamaican ginger beer.\nIngredients: Don Julio Blanco • Casamigos Reposado • Stoney Ginger Beer",
      "kind": "drink",
      "categorySlug": "cocktails",
      "published": false,
      "isAvailable": true,
      "sortOrder": 8,
      "imageUrl": "assets/images/menu/tequila-island.webp",
      "illustrative": true,
      "options": []
    },
    {
      "slug": "the-last-call",
      "name": "The Last Call",
      "description": "One for the grown folks.\nCognac and Taylor Port with a ginger beer finish.\nIngredients: Hennessy VS • D’Ussé • Taylor Port • Stoney Ginger Beer",
      "kind": "drink",
      "categorySlug": "cocktails",
      "published": false,
      "isAvailable": true,
      "sortOrder": 9,
      "imageUrl": "assets/images/menu/the-last-call.webp",
      "illustrative": true,
      "options": []
    }
  ]
};
